// Code generated by "go-enumer (github.com/mvrahden/go-enumer)"; DO NOT EDIT.

package enums

// THIS FILE IS JUST FOR TESTING PURPOSES AND DOES NOT REPRESENT
// A FULLY FLEDGED GENERATED ENUMER FILE

const (
	ValidAUndefined ValidA = 0
)