# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21', '1.22' ]

    steps:
    - name: Checkout Image
      uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build ${{ matrix.go-version }}
      run: go build -v ./...

    - name: Test ${{ matrix.go-version }}
      run: go test -cover -v ./...
